Some syntax fixing
react-bootcamp/react-101 pull request #2
Opened 2016-11-25 05:16 UTC by ybonnel

2016-11-29 20:56 UTC, mathieuancelin commented on instructions/1-your-first-component.md
> +        <button type="button" onClick={() => this.incrementCounter()}>increment</button>
Actually, you don't need a closure here as `React.createClass` will auto-bind all classes functions. By doing so you will avoid some potential performance issues.

2016-11-29 20:58 UTC, mathieuancelin commented on instructions/1-your-first-component.md
> +        <button type="button" onClick={() => this.incrementCounter()}>increment</button>
Yep, my bad. If you want to be really efficient, you'd rather use 

```javascript
this.incrementCounter = this.incrementCounter.bind(this);
```

in the constructor and keep `onClick={this.incrementCounter}` in the `<button />`

2016-11-29 20:58 UTC, mathieuancelin requested changes
Just remove the first fix and everything will be fine for this PR

2016-11-30 08:38 UTC, ybonnel commented
@mathieuancelin i didn't understand why it works with ```React.createClass```, thanks for the explain :)

2016-11-30 09:25 UTC, mathieuancelin approved these changes

2016-11-30 09:25 UTC, merged